"""Discord interface for the fingerprint visualization service.

Usage: /fingerprint image:<attachment> prediction:<true|false>
The bot returns the realistic PNG, a JSON report, and application-side usage.
"""
from __future__ import annotations

import io
import os

import discord
from discord import app_commands
from discord.ext import commands
from dotenv import load_dotenv

from service import process_bytes, report_json
from discord_bot.usage import add, current

load_dotenv()

TOKEN = os.getenv("DISCORD_BOT_TOKEN")
if not TOKEN:
    raise RuntimeError("DISCORD_BOT_TOKEN is not configured")

intents = discord.Intents.default()
bot = commands.Bot(command_prefix="!", intents=intents)


@bot.event
async def on_ready():
    await bot.tree.sync()
    print(f"Logged in as {bot.user} | slash commands synced")


@bot.tree.command(name="fingerprint", description="Process an authorized fingertip image")
@app_commands.describe(image="JPG/PNG/WebP fingertip image", prediction="Run the separate prediction/review branch")
async def fingerprint(interaction: discord.Interaction, image: discord.Attachment, prediction: bool = False):
    await interaction.response.defer(thinking=True)
    if image.content_type and not image.content_type.startswith("image/"):
        await interaction.followup.send("❌ Please attach a JPG, PNG, or WebP image.", ephemeral=True)
        return
    if image.size > 12 * 1024 * 1024:
        await interaction.followup.send("❌ Image is larger than 12 MB.", ephemeral=True)
        return

    data = await image.read()
    try:
        result = process_bytes(data, image.content_type or "image/jpeg", mode=2, zoom_scale=4, prediction=prediction)
    except Exception as exc:
        await interaction.followup.send(f"❌ Processing failed: `{exc}`", ephemeral=True)
        return

    stats = add(result["report"])
    usage_lines = []
    for item in result["report"]["ai"]["usage"]:
        usage_lines.append(f"{item.get('provider')} / {item.get('model')}: {item.get('total_tokens', 0)} tokens")
    if not usage_lines:
        usage_lines.append("No external AI provider completed this run.")

    embed = discord.Embed(title="🧬 Fingerprint Ridge Extractor", description="Realistic result generated by the local OpenCV pipeline.")
    embed.add_field(name="Quality", value=f"{result['report']['quality']['score']:.0f}/100 ({result['report']['quality']['label']})", inline=True)
    embed.add_field(name="Zoom", value=f"{result['report']['zoom_scale']}x", inline=True)
    embed.add_field(name="Prediction branch", value="ON — separate" if prediction else "OFF", inline=True)
    embed.add_field(name="AI usage", value="\n".join(usage_lines), inline=False)
    embed.add_field(name="Bot ledger", value=f"Requests: {stats['requests']}\nTokens: {stats['total_tokens']}", inline=False)
    embed.set_footer(text="Provider quotas are controlled by their accounts; the bot ledger is local accounting.")

    final_file = discord.File(io.BytesIO(result["stages"]["stage4"]), filename="fingerprint_ridges_final.png")
    report_file = discord.File(io.BytesIO(report_json(result["report"])), filename="fingerprint_report.json")
    await interaction.followup.send(embed=embed, files=[final_file, report_file])


@bot.tree.command(name="usage", description="Show local Discord-bot AI usage accounting")
async def usage(interaction: discord.Interaction):
    stats = current()
    await interaction.response.send_message(
        f"📊 **Local bot usage**\nRequests: `{stats['requests']}`\nInput tokens: `{stats['input_tokens']}`\nOutput tokens: `{stats['output_tokens']}`\nTotal tokens: `{stats['total_tokens']}`\n\nThis is accounting only, not a provider remaining-quota value."
    )


bot.run(TOKEN)
